// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Liveness / readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.HealthResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Liveness / readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/sensors": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensors"
                ],
                "summary": "List sensors",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Only sensors carrying this tag",
                        "name": "tag",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.SensorListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Registers a new sensor. The name is the immutable identifier and must be unique.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensors"
                ],
                "summary": "Create a sensor",
                "parameters": [
                    {
                        "description": "Sensor to create",
                        "name": "sensor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.CreateSensorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/httpapi.SensorResponse"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "URL of the created sensor"
                            }
                        }
                    },
                    "400": {
                        "description": "Validation failed or malformed JSON",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Name already exists",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sensors/nearest": {
            "get": {
                "description": "Returns the sensor closest to the given coordinate (great-circle distance) and the distance in metres.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensors"
                ],
                "summary": "Find the nearest sensor",
                "parameters": [
                    {
                        "maximum": 90,
                        "minimum": -90,
                        "type": "number",
                        "description": "Latitude in decimal degrees",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 180,
                        "minimum": -180,
                        "type": "number",
                        "description": "Longitude in decimal degrees",
                        "name": "lon",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.NearestSensorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No sensors stored",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sensors/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensors"
                ],
                "summary": "Get a sensor by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sensor name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.SensorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Full replacement of location and tags. Omitted tags are cleared. The name cannot be changed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensors"
                ],
                "summary": "Replace a sensor's metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sensor name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New metadata",
                        "name": "sensor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.ReplaceSensorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.SensorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Concurrent modification",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "sensors"
                ],
                "summary": "Delete a sensor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sensor name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates only the fields present in the body. At least one field is required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensors"
                ],
                "summary": "Partially update a sensor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sensor name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to change",
                        "name": "sensor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.PatchSensorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.SensorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Concurrent modification",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpapi.CreateSensorRequest": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/httpapi.LocationRequest"
                },
                "name": {
                    "type": "string",
                    "example": "roof-temp-01"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "temperature",
                        "roof"
                    ]
                }
            }
        },
        "httpapi.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "validation_failed"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpapi.FieldError"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "request is invalid"
                }
            }
        },
        "httpapi.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/httpapi.ErrorBody"
                }
            }
        },
        "httpapi.FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string",
                    "example": "location.latitude"
                },
                "message": {
                    "type": "string",
                    "example": "must be between -90 and 90"
                }
            }
        },
        "httpapi.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "httpapi.LocationRequest": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "example": 51.5074
                },
                "longitude": {
                    "type": "number",
                    "example": -0.1278
                }
            }
        },
        "httpapi.LocationResponse": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "example": 51.5074
                },
                "longitude": {
                    "type": "number",
                    "example": -0.1278
                }
            }
        },
        "httpapi.NearestSensorResponse": {
            "type": "object",
            "properties": {
                "distance_meters": {
                    "type": "number",
                    "example": 1234.5
                },
                "sensor": {
                    "$ref": "#/definitions/httpapi.SensorResponse"
                }
            }
        },
        "httpapi.PatchSensorRequest": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/httpapi.LocationRequest"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "temperature",
                        "roof"
                    ]
                }
            }
        },
        "httpapi.ReplaceSensorRequest": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/httpapi.LocationRequest"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "temperature",
                        "roof"
                    ]
                }
            }
        },
        "httpapi.SensorListResponse": {
            "type": "object",
            "properties": {
                "sensors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpapi.SensorResponse"
                    }
                }
            }
        },
        "httpapi.SensorResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-09-18T10:00:00Z"
                },
                "location": {
                    "$ref": "#/definitions/httpapi.LocationResponse"
                },
                "name": {
                    "type": "string",
                    "example": "roof-temp-01"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "temperature",
                        "roof"
                    ]
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-09-18T10:00:00Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Sensor Metadata API",
	Description:      "JSON REST API for storing and querying sensor metadata: name, GPS location and tags.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
